name = "sms-forwarder"
main = "workers.js"
compatibility_date = "2026-09-01"
workers_dev = false
[[routes]]
pattern = "sms.hzgbai.dpdns.org"
custom_domain = true
[[kv_namespaces]]
binding = "kv"
id = "656252fb8c374146bf47027f4a56827c"
[vars]
MAX_RECORDS = "200"
[observability]
enabled = true
